---
services:
  rails:
    container_name: infra-app__rails
    image: infra-app__rails
    hostname: infra-app
    build:
      target: development
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      REDIS_HOST: ${REDIS_HOST}
      CASSANDRA_HOSTS: ${CASSANDRA_HOSTS}
      PLATFORM: ${PLATFORM}
    volumes:
      - .:/app
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"

  sidekiq:
    container_name: infra-app__sidekiq
    image: infra-app__rails
    command: bash scripts/sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    container_name: infra-app__redis
    image: redis:7
    # volumes:
    #   - redis:/data

  mysql:
    container_name: infra-app__mysql
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      # - mysql:/var/lib/mysql
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql

  cassandra:
    container_name: infra-app__cassandra
    image: cassandra:4.1
    # volumes:
    #   - cassandra:/var/

# volumes:
#   redis:
#   mysql:
#   cassandra:
