---
services:
  rails:
    container_name: infra-app__rails
    image: infra-app__rails:${RAILS_ENV}
    # command: tail -f /dev/null
    hostname: rails
    build:
      target: ${RAILS_ENV}
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      mysql:
        condition: service_healthy

  sidekiq:
    container_name: infra-app__sidekiq
    image: infra-app__rails:${RAILS_ENV}
    hostname: sidekiq
    command: bash scripts/sidekiq
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    container_name: infra-app__redis
    image: redis:7.2
    volumes:
      - redis:/data

  mysql:
    container_name: infra-app__mysql
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysqlm
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda:
    container_name: infra-app__redpanda
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.9
    ports:
      - 9092:9092

  redpanda_ui:
    container_name: infra-app__redpanda_ui
    image: redpandadata/console:v2.6.1
    environment:
      KAFKA_BROKERS: redpanda:9092
    ports:
      - 8080:8080

  cassandra:
    container_name: infra-app__cassandra
    image: cassandra:4.1
    volumes:
      - cassandra:/var/

volumes:
  redis:
  mysql:
  cassandra:
