---
version: "3.9"
services:
  rails:
    container_name: infra-app__rails
    image: infra-app
    hostname: infra-app
    build: .
    # command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      - mysql
      - redis
      - cassandra

  sidekiq:
    container_name: infra-app__sidekiq
    image: infra-app
    command: bash scripts/sidekiq
    volumes:
      - .:/app

  redis:
    container_name: infra-app__redis
    image: redis:7.2
    volumes:
      - redis:/data

  mysql:
    container_name: infra-app__mysql
    image: mysql:8.3
    volumes:
      - mysql:/var/lib/mysql

  cassandra:
    container_name: infra-app__cassandra
    image: cassandra:4.1
    volumes:
      - cassandra:/var/

volumes:
  redis:
  mysql:
  cassandra:
