---
services:
  rails:
    container_name: infra-app__rails
    image: infra-app
    hostname: infra-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundler:/usr/local/bundle
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    networks:
      - infra_default
    depends_on:
      - mysql
      - sidekiq

  sidekiq:
    container_name: infra-app__sidekiq
    image: infra-app
    command: bash scripts/sidekiq
    volumes:
      - .:/app
      - bundler:/usr/local/bundle
    networks:
      - infra_default
    depends_on:
      - redis

  redis:
    container_name: infra-app__redis
    image: redis:7.2
    volumes:
      - redis:/data
    networks:
      - infra_default

  mysql:
    container_name: infra-app__mysql
    image: mysql:8.1
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - infra_default

  # cassandra:
  #   container_name: infra-app__cassandra
  #   image: cassandra:4.1
  #   volumes:
  #     - cassandra:/var/

networks:
  infra_default:

volumes:
  bundler:
  redis:
  mysql:
