---
version: '3.7'

services:
  app:
    build: .
    container_name: app
    image: app
    command: bash scripts/server
    volumes:
      - .:/app
      - bundler:/usr/local/bundle
    depends_on:
      - redis
    ports:
      - '3000:3000'

  sidekiq:
    container_name: sidekiq
    image: app
    command: bash scripts/sidekiq
    volumes:
      - .:/app
      - bundler:/usr/local/bundle
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:6.0.4
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

volumes:
  bundler:
  redis:
