---
version: "3.9"
services:
  rails:
    container_name: infra-app__rails
    image: infra-app
    hostname: infra-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_PORT: ${RAILS_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      CASSANDRA_HOSTS: ${CASSANDRA_HOSTS}
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    networks:
      - infra_default
    depends_on:
      - mysql
      - redis
      - cassandra

  sidekiq:
    container_name: infra-app__sidekiq
    image: infra-app
    command: bash scripts/sidekiq
    environment:
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - .:/app
    networks:
      - infra_default

  redis:
    container_name: infra-app__redis
    image: redis:7.2
    volumes:
      - redis:/data
    networks:
      - infra_default

  mysql:
    container_name: infra-app__mysql
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - infra_default

  cassandra:
    container_name: infra-app__cassandra
    image: cassandra:4.1
    volumes:
      - cassandra:/var/

networks:
  infra_default:

volumes:
  redis:
  mysql:
  cassandra:
