---
services:
  infra_test_app:
    container_name: infra_test_app
    image: infra_test_app
    hostname: infra-test-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash scripts/server
    env_file:
      - .dev.env
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundler:/usr/local/bundle
    ports:
      - "3000:3000"
    networks:
      - infra_default
    depends_on:
      - db
      - sidekiq

  sidekiq:
    container_name: infra_test_app-sidekiq
    image: infra_test_app
    command: bash scripts/sidekiq
    volumes:
      - .:/app
      - bundler:/usr/local/bundle
    networks:
      - infra_default
    depends_on:
      - redis

  redis:
    container_name: infra_test_app-redis
    image: redis:6.2-bullseye
    volumes:
      - redis:/data
    networks:
      - infra_default
    ports:
      - '6379:6379'

  db:
    container_name: infra_test_app-mysql
    image: mysql:8.0
    env_file:
      - .dev.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - infra_default

networks:
  infra_default:

volumes:
  bundler:
  redis:
  mysql:
