---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>
  timeout: 1000 # milliseconds

development: &development
  <<: *default
  host: <%= ENV.fetch('MYSQL_HOST') %>
  port: <%= ENV.fetch('MYSQL_PORT', 3306) %>
  database: infra_app_development
  username: <%= ENV.fetch('MYSQL_USERNAME') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>

test:
  <<: *development
  database: infra_app_test

production:
  <<: *default
  host: <%= ENV.fetch('MYSQL_HOST') %>
  port: <%= ENV.fetch('MYSQL_PORT') %>
  database: infra_app
  username: <%= ENV.fetch('MYSQL_USERNAME') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
