---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 32 } %>
  timeout: 1000 # milliseconds
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>
  port: <%= ENV.fetch('MYSQL_PORT', 3306) %>
  username: <%= ENV.fetch('MYSQL_USERNAME', 'app') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'app') %>

development: &development
  <<: *default
  database: infra_app_development

test:
  <<: *development
  database: infra_app_test

production:
  <<: *default
  database: infra_app
