---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: app_development
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  # socket: /tmp/remote.mysql.sock

test:
  <<: *development
  database: app_test

production:
  <<: *default
  database: rails_mysql_test_app
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['RAILS_MYSQL_TEST_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_MYSQL_TEST_APP_DATABASE_PASSWORD'] %>
