---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>

development: &development
  <<: *default
  database: <%= Services::Mysql::Env.database %>
  host: <%= Services::Mysql::Env.host %>
  username: <%= Services::Mysql::Env.username %>
  password: <%= Services::Mysql::Env.password %>
  port: <%= Services::Mysql::Env.port %>
  timeout: 1000 # milliseconds

test:
  <<: *development
  database: infra_app_test

production:
  <<: *default
  database: infra_app
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
