---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'a'
  host: localhost

development:
  <<: *default
  database: app
  host: 192.168.33.10
  username: app
  password: app
  port: 3306
  socket: /tmp/remote.mysql.sock
  # host: <%= ENV['DATABASE_HOST'] %>
  # port: <%= ENV['DATABASE_PORT'] %>

test:
  <<: *default
  database: rails_mysql_test_app_test

production:
  <<: *default
  database: rails_mysql_test_app
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['RAILS_MYSQL_TEST_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_MYSQL_TEST_APP_DATABASE_PASSWORD'] %>
