---
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>

development: &development
  <<: *default
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>
  database: <%= ENV.fetch('MYSQL_DATABASE', 'infra_app') %>
  username: <%= ENV.fetch('MYSQL_USERNAME', 'app') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'app') %>
  port: <%= ENV.fetch('MYSQL_PORT', 3306) %>
  timeout: 1000 # milliseconds

test:
  <<: *development
  database: infra_app_test

production:
  <<: *default
  database: infra_app
  host: <%= ENV.fetch('MYSQL_HOST') %>
  port: <%= ENV.fetch('MYSQL_PORT') %>
  username: <%= ENV.fetch('MYSQL_USERNAME') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
