
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'a'
  host: localhost

development:
  <<: *default
  database: rails_mysql_test_app_development

test:
  <<: *default
  database: rails_mysql_test_app_test

production:
  <<: *default
  database: rails_mysql_test_app_production
  username: rails_mysql_test_app
  password: <%= ENV['RAILS_MYSQL_TEST_APP_DATABASE_PASSWORD'] %>
