GRANT PROCESS ON *.* TO app@"%";

CREATE DATABASE IF NOT EXISTS infra_app_development;
GRANT INSERT,SELECT,UPDATE,DELETE,CREATE,ALTER ON infra_app_development.* TO app@"%";

CREATE DATABASE IF NOT EXISTS infra_app_test;
GRANT ALL PRIVILEGES ON infra_app_test.* TO app@"%";

CREATE DATABASE IF NOT EXISTS infra_app;
GRANT INSERT,SELECT,UPDATE,DELETE,CREATE,ALTER ON infra_app.* TO app@"%";
