---
name: build

on:
  push

jobs:
  docker_build:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Get latest commit hash
      #   run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Build Docker image
          # docker build --tag infra-app:latest --tag infra-app:${{ steps.get_commit_hash.outputs.commit_hash }} .
        run: |
          docker build --tag infra-app:latest .

      - name: Push image to registry
        run: |
          docker push registry.infra.net/infra-app:latest
