---
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: sh

jobs:
  docker_build:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the latest commit hash
        id: get_sha
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Write commit SHA to .revision file
        run: echo "${{ env.COMMIT_SHA }}" > .revision

      # - name: Build Docker image [dev]
      #   run: |
      #     docker build . \
      #       --target development \
      #       --tag registry.infra.net/infra-app:${{ env.COMMIT_SHA }} \
      #       --tag registry.infra.net/infra-app:dev

      - name: Build Docker image
        run: |-
          docker build . --target production \
            --tag registry.infra.net/infra-app:${{ env.COMMIT_SHA }} \
            --tag registry.infra.net/infra-app:prod

      # - name: Tag image
      #   run: docker tag infra-app:latest registry.infra.net/infra-app:latest

      - name: Push image to registry
        run: docker push registry.infra.net/infra-app --all-tags
