---
name: build

on:
  push:
    branches:
      - master

jobs:
  docker_build:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --tag infra-app:latest .

      - name: Tag image
        run: docker tag infra-app:latest registry.infra.net/infra-app:latest

      - name: Push image to registry
        run: docker push registry.infra.net/infra-app:latest
