---
on: push

env:
  RAILS_ENV: test

defaults:
  run:
    shell: sh

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build
        shell: sh

      - name: Start containers
        run: docker compose up rails -d
        shell: sh

      - name: Run rspec
        run: docker compose exec rails bash scripts/test
        shell: sh

      - name: Clean up
        if: always()
        run: docker compose down --volumes
        shell: sh
