# ---
# on:
#   push:
#     branches:
#       - **

# jobs:
#   test:
#     name: Run RSpec tests
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Build Docker image
#         run: docker build --tag infra-app:test .

#       - name: Run test
#         run: docker run infra-app:test rspec
